# Generated by Django 4.0.2 on 2023-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metr', models.IntegerField()),
                ('bedrooms', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('updated', models.TimeField(auto_now=True)),
                ('created', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
