# Generated by Django 4.0.2 on 2023-06-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
