# Generated by Django 4.0.2 on 2023-06-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_villa_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galleryv',
            new_name='Galleryvilla',
        ),
    ]
