# Generated by Django 4.0.2 on 2023-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_galleryv_galleryvilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='page_info1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='page_info2',
            field=models.TextField(null=True),
        ),
    ]
