# Generated by Django 4.0.2 on 2023-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
