# Generated by Django 4.0.2 on 2023-06-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_villa_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='name_en',
        ),
    ]
