# Generated by Django 4.0.2 on 2023-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_villa_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='bedrooms_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='bedrooms_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='info_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='info_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
