# Generated by Django 4.0.2 on 2023-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_villa_bedrooms_en_villa_bedrooms_tr_villa_info_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='info_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='info_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
