# Generated by Django 4.0.2 on 2023-06-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_rename_page_info1_food_page_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='page_info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='page_info_tr',
            field=models.TextField(null=True),
        ),
    ]
